<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'ezcdbexception' => '/exceptions/exception.php',
                'ezcdbfactory' => '/factory.php',
                'ezcdbhandler' => '/handler.php',
                'ezcdbhandlermssql' => '/handlers/mssql.php',
                'ezcdbhandlermysql' => '/handlers/mysql.php',
                'ezcdbhandlernotfoundexception' => '/exceptions/handler_not_found.php',
                'ezcdbhandleroracle' => '/handlers/oracle.php',
                'ezcdbhandlerpgsql' => '/handlers/pgsql.php',
                'ezcdbhandlersqlite' => '/handlers/sqlite.php',
                'ezcdbinstance' => '/instance.php',
                'ezcdbinterface' => '/interface.php',
                'ezcdbmissingparameterexception' => '/exceptions/missing_parameter.php',
                'ezcdbmssqloptions' => '/options/identifiers.php',
                'ezcdbtransactionexception' => '/exceptions/transaction.php',
                'ezcdbutilities' => '/sqlabstraction/utilities.php',
                'ezcdbutilitiesmysql' => '/sqlabstraction/implementations/utilities_mysql.php',
                'ezcdbutilitiesoracle' => '/sqlabstraction/implementations/utilities_oracle.php',
                'ezcdbutilitiespgsql' => '/sqlabstraction/implementations/utilities_pgsql.php',
                'ezcdbutilitiessqlite' => '/sqlabstraction/implementations/utilities_sqlite.php',
                'ezcquery' => '/sqlabstraction/query.php',
                'ezcquerydelete' => '/sqlabstraction/query_delete.php',
                'ezcqueryexception' => '/exceptions/query_exception.php',
                'ezcqueryexpression' => '/sqlabstraction/expression.php',
                'ezcqueryexpressionmssql' => '/sqlabstraction/implementations/expression_mssql.php',
                'ezcqueryexpressionoracle' => '/sqlabstraction/implementations/expression_oracle.php',
                'ezcqueryexpressionpgsql' => '/sqlabstraction/implementations/expression_pgsql.php',
                'ezcqueryexpressionsqlite' => '/sqlabstraction/implementations/expression_sqlite.php',
                'ezcqueryinsert' => '/sqlabstraction/query_insert.php',
                'ezcqueryinvalidexception' => '/exceptions/query/invalid.php',
                'ezcqueryinvalidparameterexception' => '/exceptions/query/invalid_parameter.php',
                'ezcqueryselect' => '/sqlabstraction/query_select.php',
                'ezcqueryselectmssql' => '/sqlabstraction/implementations/query_select_mssql.php',
                'ezcqueryselectoracle' => '/sqlabstraction/implementations/query_select_oracle.php',
                'ezcqueryselectsqlite' => '/sqlabstraction/implementations/query_select_sqlite.php',
                'ezcquerysqlitefunctions' => '/sqlabstraction/implementations/query_sqlite_function_implementations.php',
                'ezcquerysubselect' => '/sqlabstraction/query_subselect.php',
                'ezcqueryupdate' => '/sqlabstraction/query_update.php',
                'ezcqueryvariableparameterexception' => '/exceptions/query/variable_parameter.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd
